server:
  port: 1137

spring:
  application:
    name: API-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # STUDENT SERVICE
        - id: student-service
          uri: http://localhost:1134/
          predicates:
            - Path=/api/students/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuitBreaker
                fallbackUri: forward:/studentFallback

        # BOOK SERVICE
        - id: book-service
          uri: http://localhost:1135/
          predicates:
            - Path=/api/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookServiceCircuitBreaker
                fallbackUri: forward:/bookFallback
